In [56]:
import pandas as pd
import numpy as np

In [145]:
#Loading Excel file and checking the table names

In [55]:
file_path = r"C:\Users\HP\Downloads\Dangote_Refinery_Synthetic_Operations_Dataset.xlsx"
workbook = pd.ExcelFile(file_path)
workbook.sheet_names

['Refinery_Production',
 'Equipment_Data',
 'Maintenance_Data',
 'Downtime_Data',
 'Product_Quality',
 'Inventory_Data',
 'Logistics_Data',
 'Energy_Utilities',
 'HSSE_Data',
 'Workforce_Data']

In [ ]:
#starting with Table one (Refinery_Production)

In [53]:
production = pd.read_excel(
    file_path,
    sheet_name="Refinery_Production"
)

In [54]:
production.head()

,Record_ID,Date,Shift,Production_Line_ID,Processing_Unit,Product,Feedstock_Type,Crude_Input_Bbl,Planned_Production_Bbl,Actual_Production_Bbl,...,Production_Variance_Bbl,Utilization_Rate_Pct,Yield_Pct,Operating_Hours,Downtime_Hours,Energy_Consumption_MWh,Production_Cost_USD,Production_Cost_NGN,Operator_Count,Status
0,PR000001,2025-01-01,Evening,PL11,Utilities,Fuel Oil,Light Sweet Crude,808.4,903.5,672.5,...,-227.1,74.76,83.19,6.53,0.82,3.90,22669.66,3.400449e+07,8,On Stream
1,PR000002,2025-01-02,Day,PL08,Hydrogen Unit,Petrochemical Feedstock,Light Sweet Crude,1216.5,1479.0,866.3,...,-614.8,58.49,71.21,4.93,2.62,4.13,21243.23,3.186485e+07,12,On Stream
2,PR000003,2025-01-03,Night,PL03,Blending Unit,AGO,Medium Sweet Crude,8449.5,8128.0,6059.8,...,-2089.4,74.36,71.72,5.94,0.81,36.97,137671.42,2.065071e+08,4,On Stream
3,PR000004,2025-01-04,Day,PL03,Blending Unit,Jet A-1,Medium Sweet Crude,6081.3,6328.7,4750.4,...,-1713.1,73.50,78.11,6.39,1.27,24.59,90360.70,1.355411e+08,12,On Stream
4,PR000005,2025-01-05,Evening,PL11,Hydrogen Unit,Petrochemical Feedstock,Medium Sweet Crude,1557.9,1684.8,1178.4,...,-471.6,71.42,75.64,5.70,1.61,6.81,30599.58,4.589938e+07,12,On Stream

In [7]:
production.tail()

,Record_ID,Date,Shift,Production_Line_ID,Processing_Unit,Product,Feedstock_Type,Crude_Input_Bbl,Planned_Production_Bbl,Actual_Production_Bbl,...,Production_Variance_Bbl,Utilization_Rate_Pct,Yield_Pct,Operating_Hours,Downtime_Hours,Energy_Consumption_MWh,Production_Cost_USD,Production_Cost_NGN,Operator_Count,Status
15115,PR001801,2026-08-08,Night,PL06,Hydrocracker,Naphtha,Light Sweet Crude,6243.9,7713.4,4984.3,...,-2629.7,65.46,79.83,5.39,1.58,25.27,107280.87,1.609213e+08,8,Reduced Rate
15116,PR007232,2026-06-28,Evening,PL05,CDU,Jet A-1,Light Sweet Crude,5121.4,7085.5,4270.3,...,-2806.2,60.34,83.38,5.00,1.52,13.65,76724.30,1.150864e+08,6,Reduced Rate
15117,PR002168,2025-12-10,Night,PL08,Sulphur Recovery Unit,Sulphur,Medium Sweet Crude,626.8,727.5,462.3,...,-277.3,62.51,73.76,5.14,1.97,2.59,11335.93,1.700389e+07,14,On Stream
15118,PR001554,2025-12-04,Day,PL08,Hydrocracker,Jet A-1,Blended Crude,6959.9,6662.7,4870.1,...,-1682.1,74.33,69.97,5.73,0.89,20.56,127155.39,1.907331e+08,10,On Stream
15119,PR003821,2025-06-22,Night,PL02,Product Loading,AGO,Medium Sweet Crude,12239.8,12131.0,10872.0,...,-1552.2,87.51,88.82,7.83,0.07,53.16,272720.70,4.090811e+08,8,On Stream

In [33]:
production.shape

(15120, 21)

In [60]:
production.columns

Index(['Record_ID', 'Date', 'Shift', 'Production_Line_ID', 'Processing_Unit',
       'Product', 'Feedstock_Type', 'Crude_Input_Bbl',
       'Planned_Production_Bbl', 'Actual_Production_Bbl',
       'Production_Target_Bbl', 'Production_Variance_Bbl',
       'Utilization_Rate_Pct', 'Yield_Pct', 'Operating_Hours',
       'Downtime_Hours', 'Energy_Consumption_MWh', 'Production_Cost_USD',
       'Production_Cost_NGN', 'Operator_Count', 'Status'],
      dtype='object')

In [18]:
production.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15120 entries, 0 to 15119
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Record_ID                15120 non-null  object
 1   Date                     15120 non-null  datetime64[ns]
 2   Shift                    14743 non-null  object
 3   Production_Line_ID       15120 non-null  object
 4   Processing_Unit          14743 non-null  object
 5   Product                  14744 non-null  object
 6   Feedstock_Type           15120 non-null  object
 7   Crude_Input_Bbl          15120 non-null  object
 8   Planned_Production_Bbl   15120 non-null  float64
 9   Actual_Production_Bbl    15120 non-null  float64
 10  Production_Target_Bbl    15120 non-null  float64
 11  Production_Variance_Bbl  15120 non-null  float64
 12  Utilization_Rate_Pct     15120 non-null  float64
 13  Yield_Pct                15120 non-null  float64
 14  Operating_Hours          15120 non-null  float64
 15  Downtime_Hours           15120 non-null  float64
 16  Energy_Consumption_MWh   15120 non-null  float64
 17  Production_Cost_USD      15120 non-null  float64
 18  Production_Cost_NGN      15120 non-null  float64
 19  Operator_Count           15120 non-null  int64
 20  Status                   15120 non-null  object
dtypes: datetime64[ns](1), float64(11), int64(1), object(8)
memory usage: 2.4+ MB

In [ ]:
#checking for data types

In [61]:
production.dtypes

Record_ID                          object
Date                       datetime64[ns]
Shift                              object
Production_Line_ID                 object
Processing_Unit                    object
Product                            object
Feedstock_Type                     object
Crude_Input_Bbl                    object
Planned_Production_Bbl            float64
Actual_Production_Bbl             float64
Production_Target_Bbl             float64
Production_Variance_Bbl           float64
Utilization_Rate_Pct              float64
Yield_Pct                         float64
Operating_Hours                   float64
Downtime_Hours                    float64
Energy_Consumption_MWh            float64
Production_Cost_USD               float64
Production_Cost_NGN               float64
Operator_Count                      int64
Status                             object
dtype: object

In [20]:
production.dtypes.value_counts()

float64           11
object             8
datetime64[ns]     1
int64              1
Name: count, dtype: int64

In [ ]:
#checking for how many duplicates for the production table

In [8]:
production.duplicated().sum()

np.int64(80)

In [ ]:
#dropping and deleting duplicates

In [57]:
production = production.drop_duplicates()
production

,Record_ID,Date,Shift,Production_Line_ID,Processing_Unit,Product,Feedstock_Type,Crude_Input_Bbl,Planned_Production_Bbl,Actual_Production_Bbl,...,Production_Variance_Bbl,Utilization_Rate_Pct,Yield_Pct,Operating_Hours,Downtime_Hours,Energy_Consumption_MWh,Production_Cost_USD,Production_Cost_NGN,Operator_Count,Status
0,PR000001,2025-01-01,Evening,PL11,Utilities,Fuel Oil,Light Sweet Crude,808.4,903.5,672.5,...,-227.1,74.76,83.19,6.53,0.82,3.90,22669.66,3.400449e+07,8,On Stream
1,PR000002,2025-01-02,Day,PL08,Hydrogen Unit,Petrochemical Feedstock,Light Sweet Crude,1216.5,1479.0,866.3,...,-614.8,58.49,71.21,4.93,2.62,4.13,21243.23,3.186485e+07,12,On Stream
2,PR000003,2025-01-03,Night,PL03,Blending Unit,AGO,Medium Sweet Crude,8449.5,8128.0,6059.8,...,-2089.4,74.36,71.72,5.94,0.81,36.97,137671.42,2.065071e+08,4,On Stream
3,PR000004,2025-01-04,Day,PL03,Blending Unit,Jet A-1,Medium Sweet Crude,6081.3,6328.7,4750.4,...,-1713.1,73.50,78.11,6.39,1.27,24.59,90360.70,1.355411e+08,12,On Stream
4,PR000005,2025-01-05,Evening,PL11,Hydrogen Unit,Petrochemical Feedstock,Medium Sweet Crude,1557.9,1684.8,1178.4,...,-471.6,71.42,75.64,5.70,1.61,6.81,30599.58,4.589938e+07,12,On Stream
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15115,PR001801,2026-08-08,Night,PL06,Hydrocracker,Naphtha,Light Sweet Crude,6243.9,7713.4,4984.3,...,-2629.7,65.46,79.83,5.39,1.58,25.27,107280.87,1.609213e+08,8,Reduced Rate
15116,PR007232,2026-06-28,Evening,PL05,CDU,Jet A-1,Light Sweet Crude,5121.4,7085.5,4270.3,...,-2806.2,60.34,83.38,5.00,1.52,13.65,76724.30,1.150864e+08,6,Reduced Rate
15117,PR002168,2025-12-10,Night,PL08,Sulphur Recovery Unit,Sulphur,Medium Sweet Crude,626.8,727.5,462.3,...,-277.3,62.51,73.76,5.14,1.97,2.59,11335.93,1.700389e+07,14,On Stream
15118,PR001554,2025-12-04,Day,PL08,Hydrocracker,Jet A-1,Blended Crude,6959.9,6662.7,4870.1,...,-1682.1,74.33,69.97,5.73,0.89,20.56,127155.39,1.907331e+08,10,On Stream
15119,PR003821,2025-06-22,Night,PL02,Product Loading,AGO,Medium Sweet Crude,12239.8,12131.0,10872.0,...,-1552.2,87.51,88.82,7.83,0.07,53.16,272720.70,4.090811e+08,8,On Stream

In [ ]:
#looking for missing values for each columns

In [37]:
production.isnull().sum()

Record_ID                    0
Date                         0
Shift                      377
Production_Line_ID           0
Processing_Unit            377
Product                    376
Feedstock_Type               0
Crude_Input_Bbl              0
Planned_Production_Bbl       0
Actual_Production_Bbl        0
Production_Target_Bbl        0
Production_Variance_Bbl      0
Utilization_Rate_Pct         0
Yield_Pct                    0
Operating_Hours              0
Downtime_Hours               0
Energy_Consumption_MWh       0
Production_Cost_USD          0
Production_Cost_NGN          0
Operator_Count               0
Status                       0
dtype: int64

In [ ]:
#creating a missing value report

In [10]:
missing_report = pd.DataFrame({
    "Missing_Count": production.isnull().sum(),
    "Missing_Percentage": production.isnull().mean() * 100
})

missing_report = missing_report.sort_values(
    "Missing_Percentage",
    ascending=False
)

missing_report

                         Missing_Count  Missing_Percentage
Shift                              376            2.500000
Product                            376            2.500000
Processing_Unit                    375            2.493351
Record_ID                            0            0.000000
Utilization_Rate_Pct                 0            0.000000
Operator_Count                       0            0.000000
Production_Cost_NGN                  0            0.000000
Production_Cost_USD                  0            0.000000
Energy_Consumption_MWh               0            0.000000
Downtime_Hours                       0            0.000000
Operating_Hours                      0            0.000000
Yield_Pct                            0            0.000000
Production_Target_Bbl                0            0.000000
Production_Variance_Bbl              0            0.000000
Date                                 0            0.000000
Actual_Production_Bbl                0            0.000000
Planned_Production_Bbl               0            0.000000
Crude_Input_Bbl                      0            0.000000
Feedstock_Type                       0            0.000000
Production_Line_ID                   0            0.000000
Status                               0            0.000000

In [ ]:
#checking for unique values for product column

In [11]:
production["Product"].unique()

array(['Fuel Oil', 'Petrochemical Feedstock', 'AGO', 'Jet A-1', 'Naphtha',
       'Sulphur', 'PMS', nan, 'LPG', 'jet a-1', 'petrochemical feedstock',
       ' AGO ', 'pms', ' Sulphur ', 'naphtha', 'ago', 'sulphur',
       ' Fuel Oil ', 'JET A-1', ' PMS ', ' Jet A-1 ', 'NAPHTHA',
       ' Petrochemical Feedstock ', 'fuel oil', 'FUEL OIL',
       'PETROCHEMICAL FEEDSTOCK', ' Naphtha ', 'lpg', 'SULPHUR'],
      dtype=object)

In [58]:
production["Product"] = production["Product"].astype(str).str.strip().str.title()

In [59]:
production["Product"].unique()

array(['Fuel Oil', 'Petrochemical Feedstock', 'Ago', 'Jet A-1', 'Naphtha',
       'Sulphur', 'Pms', 'Nan', 'Lpg'], dtype=object)

In [ ]:
#checking for unique values for Status column

In [14]:
production["Status"].unique()

array(['On Stream', 'Reduced Rate', 'Shutdown', 'On Stream ',
       'Reduced Rate '], dtype=object)

In [60]:
production["Status"] = production["Status"].astype(str).str.strip().str.title()

In [61]:
production["Status"].unique()

array(['On Stream', 'Reduced Rate', 'Shutdown'], dtype=object)

In [18]:
production["Processing_Unit"].unique()

array(['Utilities', 'Hydrogen Unit', 'Blending Unit', nan,
       'Sulphur Recovery Unit', 'Diesel Hydrotreater', 'Reforming Unit',
       'CDU', 'Product Loading', 'Naphtha Hydrotreater', 'Kerosene Unit',
       'Hydrocracker'], dtype=object)

In [ ]:
#Date cleaning and validity

In [21]:
production["Date"].tail(20)

14980   2026-01-24
14981   2026-01-25
14982   2026-01-26
14983   2026-01-27
14984   2026-01-28
14985   2026-01-29
14986   2026-01-30
14987   2026-01-31
14988   2026-02-01
14989   2026-02-02
14990   2026-02-03
14991   2026-02-04
14992   2026-02-05
14993   2026-02-06
14994   2026-02-07
14995   2026-02-08
14996   2026-02-09
14997   2026-02-10
14998   2026-02-11
14999   2026-02-12
Name: Date, dtype: datetime64[ns]

In [22]:
production['Date'].dtype

dtype('<M8[ns]')

In [33]:
production['Date'] = pd.to_datetime(production['Date'], errors='coerce')

In [24]:
production['Date'].isnull().sum()

np.int64(0)

In [71]:
production['Date'].min()

Timestamp('2025-01-01 00:00:00')

In [72]:
production['Date'].max()

Timestamp('2026-11-04 00:00:00')

In [26]:
production[(production['Date'] > '2025-01-01') | (production['Date'] < '2026-11-04')]

,Record_ID,Date,Shift,Production_Line_ID,Processing_Unit,Product,Feedstock_Type,Crude_Input_Bbl,Planned_Production_Bbl,Actual_Production_Bbl,...,Production_Variance_Bbl,Utilization_Rate_Pct,Yield_Pct,Operating_Hours,Downtime_Hours,Energy_Consumption_MWh,Production_Cost_USD,Production_Cost_NGN,Operator_Count,Status
0,PR000001,2025-01-01,Evening,PL11,Utilities,Fuel Oil,Light Sweet Crude,808.4,903.5,672.5,...,-227.1,74.76,83.19,6.53,0.82,3.90,22669.66,3.400449e+07,8,On Stream
1,PR000002,2025-01-02,Day,PL08,Hydrogen Unit,Petrochemical Feedstock,Light Sweet Crude,1216.5,1479.0,866.3,...,-614.8,58.49,71.21,4.93,2.62,4.13,21243.23,3.186485e+07,12,On Stream
2,PR000003,2025-01-03,Night,PL03,Blending Unit,Ago,Medium Sweet Crude,8449.5,8128.0,6059.8,...,-2089.4,74.36,71.72,5.94,0.81,36.97,137671.42,2.065071e+08,4,On Stream
3,PR000004,2025-01-04,Day,PL03,Blending Unit,Jet A-1,Medium Sweet Crude,6081.3,6328.7,4750.4,...,-1713.1,73.50,78.11,6.39,1.27,24.59,90360.70,1.355411e+08,12,On Stream
4,PR000005,2025-01-05,Evening,PL11,Hydrogen Unit,Petrochemical Feedstock,Medium Sweet Crude,1557.9,1684.8,1178.4,...,-471.6,71.42,75.64,5.70,1.61,6.81,30599.58,4.589938e+07,12,On Stream
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,PR014996,2026-02-08,Day,PL10,Sulphur Recovery Unit,Sulphur,Medium Sweet Crude,509.9,835.3,433.4,...,-421.0,50.73,85.00,4.47,3.37,2.94,11680.44,1.752067e+07,16,Reduced Rate
14996,PR014997,2026-02-09,Evening,PL02,Reforming Unit,Pms,Light Sweet Crude,19663.5,17811.3,15157.1,...,-2730.4,84.74,77.08,6.74,0.34,92.27,283870.07,4.258051e+08,16,On Stream
14997,PR014998,2026-02-10,Evening,PL04,Kerosene Unit,Nan,Blended Crude,8163.7,6222.2,5943.6,...,-96.6,98.40,72.81,7.76,0.20,39.19,174902.47,2.623537e+08,15,On Stream
14998,PR014999,2026-02-11,NaN,PL03,Sulphur Recovery Unit,Sulphur,Light Sweet Crude,491.2,780.8,420.2,...,-356.0,54.13,85.55,4.60,1.94,2.93,10443.85,1.566578e+07,17,On Stream
14999,PR015000,2026-02-12,Evening,PL04,Hydrocracker,Naphtha,Blended Crude,5502,5556.0,4385.8,...,-1011.0,81.27,79.71,6.82,0.49,23.97,73227.36,1.098410e+08,10,On Stream

In [ ]:
#converting Crude_input_bbl to float

In [35]:
production['Crude_Input_Bbl'] = pd.to_numeric(production['Crude_Input_Bbl'], errors='coerce')

In [28]:
production['Crude_Input_Bbl'].dtype

dtype('float64')

In [29]:
production['Operator_Count'].dtype

dtype('int64')

In [ ]:
#Treating invalid operational records

In [30]:
production[(production['Operating_Hours'] == 0) & (production['Actual_Production_Bbl'] > 0)]

,Record_ID,Date,Shift,Production_Line_ID,Processing_Unit,Product,Feedstock_Type,Crude_Input_Bbl,Planned_Production_Bbl,Actual_Production_Bbl,...,Production_Variance_Bbl,Utilization_Rate_Pct,Yield_Pct,Operating_Hours,Downtime_Hours,Energy_Consumption_MWh,Production_Cost_USD,Production_Cost_NGN,Operator_Count,Status
1340,PR001341,2025-05-05,Day,PL07,Diesel Hydrotreater,Ago,Medium Sweet Crude,11096.1,10607.5,8064.9,...,-2737.6,74.66,72.68,0.0,0.71,40.87,252910.54,3.793658e+08,4,On Stream
1442,PR001443,2025-08-15,Night,PL04,Utilities,Fuel Oil,Light Sweet Crude,1034.2,1010.8,906.9,...,-127.1,87.71,87.69,0.0,0.46,5.52,15160.70,2.274104e+07,16,Reduced Rate
5455,PR005456,2026-08-15,Night,PL01,Utilities,Fuel Oil,Light Sweet Crude,1739.6,1824.3,1522.6,...,-274.3,84.73,87.53,0.0,0.15,9.88,42634.82,6.395223e+07,12,On Stream
7664,PR007665,2026-01-04,Day,PL05,Hydrogen Unit,Petrochemical Feedstock,Light Sweet Crude,1912.6,2256.5,1692.0,...,-584.6,74.32,88.47,0.0,0.35,10.72,44895.64,6.734346e+07,8,On Stream
11996,PR011997,2026-03-21,Day,PL03,Reforming Unit,Pms,Light Sweet Crude,15528.5,14438.7,12461.6,...,-1816.3,87.28,80.25,0.0,0.32,65.89,207323.16,3.109847e+08,15,On Stream

In [ ]:
#flagging rows where Operating_Hours is zero but production was made

In [36]:
production['OperatingTime_DataQualityFlag'] = production.loc[(production['Operating_Hours'] == 0) & (production['Actual_Production_Bbl'] > 0),'OperatingTime_DataQualityFlag'] = 'Zero_Hours_With_Production'

In [37]:
production[(production['Downtime_Hours'] > 0) & (production['Operating_Hours'] == 0)]

,Record_ID,Date,Shift,Production_Line_ID,Processing_Unit,Product,Feedstock_Type,Crude_Input_Bbl,Planned_Production_Bbl,Actual_Production_Bbl,...,Utilization_Rate_Pct,Yield_Pct,Operating_Hours,Downtime_Hours,Energy_Consumption_MWh,Production_Cost_USD,Production_Cost_NGN,Operator_Count,Status,OperatingTime_DataQualityFlag
1340,PR001341,2025-05-05,Day,PL07,Diesel Hydrotreater,AGO,Medium Sweet Crude,11096.1,10607.5,8064.9,...,74.66,72.68,0.0,0.71,40.87,252910.54,3.793658e+08,4,On Stream,Zero_Hours_With_Production
1442,PR001443,2025-08-15,Night,PL04,Utilities,Fuel Oil,Light Sweet Crude,1034.2,1010.8,906.9,...,87.71,87.69,0.0,0.46,5.52,15160.70,2.274104e+07,16,Reduced Rate,Zero_Hours_With_Production
5455,PR005456,2026-08-15,Night,PL01,Utilities,Fuel Oil,Light Sweet Crude,1739.6,1824.3,1522.6,...,84.73,87.53,0.0,0.15,9.88,42634.82,6.395223e+07,12,On Stream,Zero_Hours_With_Production
7664,PR007665,2026-01-04,Day,PL05,Hydrogen Unit,Petrochemical Feedstock,Light Sweet Crude,1912.6,2256.5,1692.0,...,74.32,88.47,0.0,0.35,10.72,44895.64,6.734346e+07,8,On Stream,Zero_Hours_With_Production
11996,PR011997,2026-03-21,Day,PL03,Reforming Unit,PMS,Light Sweet Crude,15528.5,14438.7,12461.6,...,87.28,80.25,0.0,0.32,65.89,207323.16,3.109847e+08,15,On Stream,Zero_Hours_With_Production

In [38]:
production['Utilization_DataQualityFlag'] = production.loc[production['Utilization_Rate_Pct'] > 100, 'Utilization_DataQualityFlag'] = 'Utilization_Over_100'

In [39]:
production[production['Utilization_Rate_Pct'] > 100]

,Record_ID,Date,Shift,Production_Line_ID,Processing_Unit,Product,Feedstock_Type,Crude_Input_Bbl,Planned_Production_Bbl,Actual_Production_Bbl,...,Yield_Pct,Operating_Hours,Downtime_Hours,Energy_Consumption_MWh,Production_Cost_USD,Production_Cost_NGN,Operator_Count,Status,OperatingTime_DataQualityFlag,Utilization_DataQualityFlag
490,PR000491,2026-05-06,Evening,PL11,Kerosene Unit,Jet A-1,Light Sweet Crude,11097.5,7824.8,7653.4,...,68.97,7.57,0.25,30.85,217390.03,3.260851e+08,6,Shutdown,Zero_Hours_With_Production,Utilization_Over_100
1480,PR001481,2025-09-22,Night,PL02,Diesel Hydrotreater,AGO,Medium Sweet Crude,10751.2,8762.8,8616.3,...,80.14,7.61,0.36,47.90,126226.58,1.893399e+08,5,On Stream,Zero_Hours_With_Production,Utilization_Over_100
1844,PR001845,2025-01-21,Evening,PL05,Hydrogen Unit,Petrochemical Feedstock,Medium Sweet Crude,2277.6,1986.6,1988.2,...,87.29,7.70,0.14,8.40,40100.43,6.015064e+07,10,Reduced Rate,Zero_Hours_With_Production,Utilization_Over_100
2137,PR002138,2025-11-10,Night,PL04,Product Loading,Jet A-1,Medium Sweet Crude,9162.5,6659.3,6563.1,...,71.63,7.84,0.07,32.78,207996.68,3.119950e+08,5,On Stream,Zero_Hours_With_Production,Utilization_Over_100
2191,PR002192,2026-01-03,Night,PL06,Hydrogen Unit,Petrochemical Feedstock,Blended Crude,3217.3,2793.7,2794.5,...,86.86,7.88,0.08,14.02,84105.25,1.261579e+08,6,On Stream,Zero_Hours_With_Production,Utilization_Over_100
2480,PR002481,2025-02-18,Night,PL04,Product Loading,Jet A-1,Medium Sweet Crude,9421.9,7505.7,7613.3,...,80.80,7.81,0.03,50.30,154143.90,2.312158e+08,5,On Stream,Zero_Hours_With_Production,Utilization_Over_100
2785,PR002786,2025-12-20,Night,PL12,Blending Unit,PMS,Medium Sweet Crude,16705.2,15308.2,15005.2,...,89.82,7.80,0.14,61.87,499450.02,7.491750e+08,15,On Stream,Zero_Hours_With_Production,Utilization_Over_100
2817,PR002818,2026-01-21,Day,PL10,Utilities,Fuel Oil,Light Sweet Crude,2180.3,1889.9,1618.4,...,74.23,6.64,0.51,11.17,31601.93,4.740290e+07,16,On Stream,Zero_Hours_With_Production,Utilization_Over_100
3011,PR003012,2026-08-03,Evening,PL02,Hydrogen Unit,Petrochemical Feedstock,Medium Sweet Crude,1900.8,2280.2,1493.0,...,78.55,5.53,1.16,7.04,30985.40,4.647809e+07,9,On Stream,Zero_Hours_With_Production,Utilization_Over_100
3126,PR003127,2025-03-28,Night,PL05,Hydrogen Unit,Petrochemical Feedstock,Blended Crude,1917.7,1546.4,1566.1,...,81.66,7.88,0.01,5.29,47947.23,7.192085e+07,16,On Stream,Zero_Hours_With_Production,Utilization_Over_100
3223,PR003224,2025-07-03,Day,PL07,Diesel Hydrotreater,AGO,Light Sweet Crude,14238.7,12112.4,11898.9,...,83.57,7.65,0.28,66.13,369578.99,5.543685e+08,5,On Stream,Zero_Hours_With_Production,Utilization_Over_100
3463,PR003464,2026-02-28,Night,PL06,CDU,AGO,Light Sweet Crude,11964.3,8805.5,8897.7,...,74.37,7.85,0.10,48.85,166133.30,2.492000e+08,13,On Stream,Zero_Hours_With_Production,Utilization_Over_100
3510,PR003511,2026-04-16,Evening,PL04,Naphtha Hydrotreater,NaN,Medium Sweet Crude,7918.0,5912.7,6056.0,...,76.48,7.93,0.06,32.08,191473.67,2.872105e+08,17,On Stream,Zero_Hours_With_Production,Utilization_Over_100
3752,PR003753,2025-04-15,Day,PL04,Naphtha Hydrotreater,PMS,Medium Sweet Crude,9091.3,8638.0,8060.2,...,88.66,7.26,0.38,38.66,116647.19,1.749708e+08,14,On Stream,Zero_Hours_With_Production,Utilization_Over_100
4189,PR004190,2026-06-26,Day,PL02,Diesel Hydrotreater,AGO,Medium Sweet Crude,11528.4,10584.5,10581.7,...,91.79,7.77,0.22,41.36,365272.48,5.479087e+08,7,On Stream,Zero_Hours_With_Production,Utilization_Over_100
4267,PR004268,2025-01-12,Evening,PL08,Reforming Unit,Naphtha,Light Sweet Crude,6245.6,4424.2,4386.5,...,70.23,7.90,0.09,25.87,141052.72,2.115791e+08,5,On Stream,Zero_Hours_With_Production,Utilization_Over_100
4390,PR004391,2025-05-15,Night,PL07,Product Loading,Fuel Oil,Light Sweet Crude,1615.1,1172.2,1154.8,...,71.50,7.63,0.28,5.27,35848.35,5.377252e+07,13,On Stream,Zero_Hours_With_Production,Utilization_Over_100
4810,PR004811,2026-07-09,Day,PL02,Reforming Unit,PMS,Light Sweet Crude,19203.5,16317.4,16497.9,...,85.91,7.79,0.19,95.10,199157.79,2.987367e+08,4,On Stream,Zero_Hours_With_Production,Utilization_Over_100
4939,PR004940,2025-03-17,Night,PL01,NaN,Sulphur,Medium Sweet Crude,425.2,388.6,308.0,...,72.43,6.54,0.47,1.22,7116.22,1.067432e+07,14,On Stream,Zero_Hours_With_Production,Utilization_Over_100
5137,PR005138,2025-10-01,Day,PL01,Utilities,Fuel Oil,Blended Crude,1782.6,1466.9,1453.9,...,81.56,7.81,0.18,9.48,46562.40,6.984361e+07,15,On Stream,Zero_Hours_With_Production,Utilization_Over_100
5520,PR005521,2025-02-18,Evening,PL05,Sulphur Recovery Unit,Sulphur,Light Sweet Crude,710.2,598.3,605.3,...,85.23,7.80,0.18,4.13,15264.22,2.289633e+07,14,Reduced Rate,Zero_Hours_With_Production,Utilization_Over_100
7594,PR007595,2025-10-26,Night,PL10,Utilities,Fuel Oil,Light Sweet Crude,2029.0,1436.3,1469.2,...,72.41,7.87,0.11,9.40,17852.76,2.677913e+07,10,On Stream,Zero_Hours_With_Production,Utilization_Over_100
8164,PR008165,2025-09-18,Evening,PL11,Kerosene Unit,Jet A-1,Medium Sweet Crude,4160.9,6311.8,3693.5,...,88.77,4.72,2.07,14.58,85257.96,1.278869e+08,13,On Stream,Zero_Hours_With_Production,Utilization_Over_100
8279,PR008280,2026-01-11,Night,PL12,CDU,AGO,Light Sweet Crude,14897.9,13479.8,13419.5,...,90.08,7.95,0.03,90.34,239605.66,3.594085e+08,16,On Stream,Zero_Hours_With_Production,Utilization_Over_100
8293,PR008294,2026-01-25,Night,PL06,CDU,Naphtha,Light Sweet Crude,5446.8,4146.9,4239.5,...,77.83,7.92,0.08,23.69,99167.27,1.487509e+08,6,On Stream,Zero_Hours_With_Production,Utilization_Over_100
9053,PR009054,2026-06-26,Night,PL11,Blending Unit,AGO,Blended Crude,11504.7,9626.6,9772.6,...,84.94,7.90,0.05,58.33,265851.26,3.987769e+08,8,Reduced Rate,Zero_Hours_With_Production,Utilization_Over_100
9193,PR009194,2025-03-15,Day,PL02,CDU,AGO,Medium Sweet Crude,13278.8,10864.6,11038.6,...,83.13,7.88,0.11,49.26,264142.42,3.962136e+08,16,On Stream,Zero_Hours_With_Production,Utilization_Over_100
9387,PR009388,2025-09-25,Evening,PL08,Kerosene Unit,Jet A-1,Blended Crude,6133.4,5333.1,5258.2,...,85.73,7.74,0.17,18.45,136413.06,2.046196e+08,6,On Stream,Zero_Hours_With_Production,Utilization_Over_100
9556,PR009557,2026-03-13,Day,PL12,Reforming Unit,Naphtha,Light Sweet Crude,6194.6,5452.3,5388.0,...,86.98,7.74,0.17,28.16,80455.19,1.206828e+08,16,Reduced Rate,Zero_Hours_With_Production,Utilization_Over_100
9730,PR009731,2025-01-03,Day,PL03,Diesel Hydrotreater,AGO,Medium Sweet Crude,9034.8,6755.1,6795.9,...,75.22,7.78,0.10,34.28,236691.26,3.550369e+08,12,On Stream,Zero_Hours_With_Production,Utilization_Over_100
10086,PR010087,2025-12-25,Day,PL11,Blending Unit,NaN,Medium Sweet Crude,15757.4,11252.9,11013.1,...,69.89,7.55,0.43,50.10,355661.24,5.334919e+08,4,On Stream,Zero_Hours_With_Production,Utilization_Over_100
10264,PR010265,2026-06-21,NaN,PL12,Sulphur Recovery Unit,Sulphur,Blended Crude,853.1,736.9,722.6,...,84.71,7.74,0.17,3.23,21868.50,3.280275e+07,8,On Stream,Zero_Hours_With_Production,Utilization_Over_100
10503,PR010504,2025-06-17,Day,PL10,Diesel Hydrotreater,AGO,Medium Sweet Crude,6475.6,6953.0,5870.2,...,90.65,6.90,0.19,20.04,132398.92,1.985984e+08,7,On Stream,Zero_Hours_With_Production,Utilization_Over_100
11211,PR011212,2025-09-25,Evening,PL05,Reforming Unit,PMS,Blended Crude,14722.9,9961.5,10089.4,...,68.53,7.81,0.18,49.58,315266.28,4.728994e+08,17,Reduced Rate,Zero_Hours_With_Production,Utilization_Over_100
11365,PR011366,2026-02-26,Night,PL07,Naphtha Hydrotreater,Naphtha,Blended Crude,8939.4,7262.5,7125.1,...,79.70,7.57,0.31,49.16,126884.32,1.903265e+08,11,On Stream,Zero_Hours_With_Production,Utilization_Over_100
11583,PR011584,2025-02-01,Day,PL05,Sulphur Recovery Unit,Sulphur,Medium Sweet Crude,831.0,613.0,628.9,...,75.68,7.94,0.02,3.71,15644.16,2.346624e+07,5,On Stream,Zero_Hours_With_Production,Utilization_Over_100
11915,PR011916,2025-12-30,Day,PL07,Naphtha Hydrotreater,PMS,Light Sweet Crude,14681.3,13175.2,10903.1,...,74.27,7.18,0.48,71.70,278591.20,4.178868e+08,15,On Stream,Zero_Hours_With_Production,Utilization_Over_100
12161,PR012162,2025-01-02,Night,PL08,Naphtha Hydrotreater,PMS,Blended Crude,10269.8,11253.9,8687.4,...,84.59,6.58,0.61,41.85,132003.93,1.980059e+08,10,Reduced Rate,Zero_Hours_With_Production,Utilization_Over_100
12182,PR012183,2025-01-23,Evening,PL08,Blending Unit,PMS,Light Sweet Crude,16850.3,13447.8,13532.0,...,80.31,7.74,0.10,59.32,322825.79,4.842387e+08,11,On Stream,Zero_Hours_With_Production,Utilization_Over_100
13588,PR013589,2025-08-01,Evening,PL12,Hydrocracker,Jet A-1,Blended Crude,10278.4,7489.8,7440.4,...,72.39,7.68,0.23,28.11,221982.59,3.329739e+08,15,On Stream,Zero_Hours_With_Production,Utilization_Over_100
13639,PR013640,2025-09-21,Evening,PL06,Utilities,Fuel Oil,Blended Crude,1868.5,1718.9,1692.6,...,90.59,7.71,0.22,9.77,32836.98,4.925547e+07,8,On Stream,Zero_Hours_With_Production,Utilization_Over_100
13942,PR013943,2026-07-21,Evening,PL01,Kerosene Unit,Jet A-1,Medium Sweet Crude,8797.9,7949.8,8019.1,...,91.15,7.80,0.17,36.96,233317.69,3.499765e+08,5,On Stream,Zero_Hours_With_Production,Utilization_Over_100
14814,PR014815,2025-08-11,Day,PL06,Diesel Hydrotreater,AGO,Medium Sweet Crude,12794.8,10464.7,10454.9,...,81.71,7.70,0.09,72.93,141558.01,2.123370e+08,4,On Stream,Zero_Hours_With_Production,Utilization_Over_100

In [ ]:
#Treating Outliers

In [ ]:
#Production Output Data Check

In [62]:
production['Actual_Production_Bbl'].describe()

count    15040.000000
mean      4882.367697
std       3635.314348
min         38.100000
25%       1487.700000
50%       4392.150000
75%       7303.825000
max      19056.000000
Name: Actual_Production_Bbl, dtype: float64

In [41]:
Q1 = production['Actual_Production_Bbl'].quantile(0.25)
Q3 = production['Actual_Production_Bbl'].quantile(0.75)

IQR = Q3-Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [65]:
production['DQ_Issues'] = production['DQ_Issues'].fillna('')

outlier_condition = (production['Actual_Production_Bbl'] < lower_bound) | (production['Actual_Production_Bbl'] > upper_bound)

production.loc[outlier_condition, 'DQ_Issues'] += 'IQR_Outlier|'
production['DQ_Issues'].value_counts()

DQ_Issues
                15000
IQR_Outlier|       40
Name: count, dtype: int64

In [64]:
production['DQ_Issues'] = ''
print('Column created/checked')

Column created/checked

In [46]:
outlier_condition = (production['Actual_Production_Bbl'] < lower_bound) | (production['Actual_Production_Bbl'] > upper_bound)
print(f"Found {outlier_condition.sum()} outliers")

Found 41 outliers

In [48]:
production['Operating_Hours'].describe()

#Operating Hours Data Check: Clean, no outliers to remove

count    15120.000000
mean         6.121684
std          1.103943
min          0.000000
25%          5.660000
50%          6.330000
75%          6.850000
max          7.980000
Name: Operating_Hours, dtype: float64

In [ ]:
#Downtime Data Check
#Treating Downtime Outlier

In [47]:
production['Downtime_Hours'].describe()

count    15120.000000
mean         1.171851
std          1.415781
min          0.000000
25%          0.440000
50%          0.850000
75%          1.482500
max         32.200000
Name: Downtime_Hours, dtype: float64

In [66]:
Q1 = production['Downtime_Hours'].quantile(0.25)
Q3 = production['Downtime_Hours'].quantile(0.75)

IQR = Q3-Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Lower Bound: {lower_bound:.2f}, Upper Bound: {upper_bound:.2f}")

Lower Bound: -1.14, Upper Bound: 3.07

In [67]:
production['DQ_Issues'] = ''

production['DQ_Issues'] = production['DQ_Issues'].fillna('')

outlier_condition = (production['Downtime_Hours'] < lower_bound) | (production['Downtime_Hours'] > upper_bound)

production.loc[outlier_condition, 'DQ_Issues'] += 'Downtime_IQR_Outlier|'
production['DQ_Issues'].value_counts()

DQ_Issues
                         14344
Downtime_IQR_Outlier|      696
Name: count, dtype: int64

In [68]:
outliers = production[outlier_condition].copy()
outliers[['Downtime_Hours', 'DQ_Issues']]

       Downtime_Hours              DQ_Issues
9                3.65  Downtime_IQR_Outlier|
28               3.64  Downtime_IQR_Outlier|
38               4.05  Downtime_IQR_Outlier|
48               4.07  Downtime_IQR_Outlier|
49               5.80  Downtime_IQR_Outlier|
...               ...                    ...
14969            3.54  Downtime_IQR_Outlier|
14978            3.29  Downtime_IQR_Outlier|
14995            3.37  Downtime_IQR_Outlier|
15081           22.00  Downtime_IQR_Outlier|
15095           21.22  Downtime_IQR_Outlier|

[696 rows x 2 columns]

In [ ]:
# Moving to Table two and there (Equipment and maintenance tables)

In [69]:
equipment = pd.read_excel(
    file_path,
    sheet_name="Equipment_Data"
)

maintenance = pd.read_excel(
    file_path,
    sheet_name="Maintenance_Data"
)

In [ ]:
#Investigating IDs that is in maintenance but not in Equipment

#Answer thay all matches

In [70]:
invalid_equipment_ids = maintenance[~maintenance["Equipment_ID"].isin(equipment["Equipment_ID"])
]

In [71]:
invalid_equipment_ids

Empty DataFrame
Columns: [Maintenance_ID, Equipment_ID, Date, Processing_Unit, Maintenance_Type, Failure_Mode, Root_Cause, Start_Time, End_Time, Downtime_Hours, MTTR_Hours, Estimated_MTBF_Hours, Labor_Hours, Spare_Parts_Cost_USD, Labor_Cost_USD, Total_Maintenance_Cost_USD, Total_Maintenance_Cost_NGN, Production_Loss_Bbl, Production_Loss_USD, Priority, Technician_Count, Maintenance_Status]
Index: []

[0 rows x 22 columns]

In [163]:
equipment.columns

Index(['Equipment_ID', 'Equipment_Name', 'Processing_Unit', 'Equipment_Type',
       'Manufacturer', 'Installation_Year', 'Criticality', 'Operating_Status',
       'Operating_Hours', 'Failure_Count', 'Downtime_Hours', 'MTBF_Hours',
       'MTTR_Hours', 'Maintenance_Type', 'Maintenance_Cost_USD',
       'Maintenance_Cost_NGN', 'Last_Maintenance_Date',
       'Next_Maintenance_Date', 'Failure_Mode', 'Root_Cause',
       'Reliability_Score'],
      dtype='object')

In [164]:
maintenance.columns

Index(['Maintenance_ID', 'Equipment_ID', 'Date', 'Processing_Unit',
       'Maintenance_Type', 'Failure_Mode', 'Root_Cause', 'Start_Time',
       'End_Time', 'Downtime_Hours', 'MTTR_Hours', 'Estimated_MTBF_Hours',
       'Labor_Hours', 'Spare_Parts_Cost_USD', 'Labor_Cost_USD',
       'Total_Maintenance_Cost_USD', 'Total_Maintenance_Cost_NGN',
       'Production_Loss_Bbl', 'Production_Loss_USD', 'Priority',
       'Technician_Count', 'Maintenance_Status'],
      dtype='object')

In [175]:
equipment["Processing_Unit"].unique()

array(['CDU', 'Hydrocracker', 'Diesel Hydrotreater',
       'Naphtha Hydrotreater', 'Kerosene Unit', 'Reforming Unit',
       'Sulphur Recovery Unit', 'Hydrogen Unit', 'Utilities',
       'Blending Unit', 'Product Loading'], dtype=object)

In [ ]:
#Moving to Downtime Table

In [72]:
downtime = pd.read_excel(file_path, sheet_name="Downtime_Data")

In [73]:
downtime.columns

Index(['Downtime_ID', 'Date', 'Shift', 'Production_Line_ID', 'Processing_Unit',
       'Equipment_ID', 'Downtime_Category', 'Root_Cause', 'Failure_Mode',
       'Planned_Unplanned', 'Start_Time', 'End_Time', 'Downtime_Hours',
       'Production_Loss_Bbl', 'Estimated_Loss_USD', 'Severity',
       'Responsible_Department', 'Resolution', 'Recurrence_Flag'],
      dtype='object')

In [74]:
#correcting downtime category which has numerous namings

downtime['Downtime_Category'] = downtime['Downtime_Category'].astype(str).str.strip().str.title()

In [75]:
downtime['Downtime_Category'].unique()

array(['Equipment Failure', 'Feedstock Delay', 'Power Interruption',
       'Process Upset', 'Planned Maintenance', 'Safety Shutdown',
       'Product Changeover', 'Unplanned Maintenance', 'Utility Failure',
       'Instrumentation Failure', 'Weather/Marine Delay', 'Other'],
      dtype=object)

In [190]:
downtime['Downtime_Hours'].describe()

count    5055.000000
mean        2.253607
std         2.792050
min        -4.921346
25%         0.925000
50%         1.650000
75%         2.810000
max        63.490000
Name: Downtime_Hours, dtype: float64

In [76]:
Q1 = downtime['Downtime_Hours'].quantile(0.25)
Q3 = downtime['Downtime_Hours'].quantile(0.75)

IQR = Q3-Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f'Lower Bound: {lower_bound:.2f}, Upper Bound: {upper_bound:.2f}')

Lower Bound: -1.90, Upper Bound: 5.64

In [77]:
downtime['DowntimeDataIssue'] = ''

downtime['DowntimeDataIssue'] = downtime['DowntimeDataIssue'].fillna('')
outlier_condition = (downtime['Downtime_Hours'] < lower_bound) | (downtime['Downtime_Hours'] > upper_bound)

downtime.loc[outlier_condition, 'DowntimeDataIssue'] += 'IQR_Outlier|'
downtime['DowntimeDataIssue'].value_counts()

DowntimeDataIssue
                4822
IQR_Outlier|     233
Name: count, dtype: int64

In [78]:
outliers = downtime[outlier_condition].copy()
outliers[['Downtime_Hours', 'DowntimeDataIssue']]

      Downtime_Hours DowntimeDataIssue
24              7.67      IQR_Outlier|
31              5.72      IQR_Outlier|
48              8.05      IQR_Outlier|
61              6.43      IQR_Outlier|
150             5.76      IQR_Outlier|
...              ...               ...
4998            9.61      IQR_Outlier|
5003           26.82      IQR_Outlier|
5020           15.75      IQR_Outlier|
5030           28.69      IQR_Outlier|
5054           38.64      IQR_Outlier|

[233 rows x 2 columns]

In [79]:
product_quality = pd.read_excel(file_path, sheet_name="Product_Quality")
inventory = pd.read_excel(file_path, sheet_name="Inventory_Data")
logistics = pd.read_excel(file_path, sheet_name="Logistics_Data")
energy_utilities = pd.read_excel(file_path, sheet_name="Energy_Utilities")
hsse = pd.read_excel(file_path, sheet_name="HSSE_Data")
workforce = pd.read_excel(file_path, sheet_name="Workforce_Data")

In [80]:
output_path = r"C:\Users\HP\Downloads\Dangote_Refinery_Cleaned_Data.xlsx"

with pd.ExcelWriter(output_path, engine="openpyxl") as writer:

    # Cleaned tables
    production.to_excel(writer, sheet_name="Refinery_Production", index=False)
    equipment.to_excel(writer, sheet_name="Equipment_Data", index=False)
    maintenance.to_excel(writer, sheet_name="Maintenance_Data", index=False)
    downtime.to_excel(writer, sheet_name="Downtime_Data", index=False)

    # Other verified tables
    product_quality.to_excel(writer, sheet_name="Product_Quality", index=False)
    inventory.to_excel(writer, sheet_name="Inventory_Data", index=False)
    logistics.to_excel(writer, sheet_name="Logistics_Data", index=False)
    energy_utilities.to_excel(writer, sheet_name="Energy_Utilities", index=False)
    hsse.to_excel(writer, sheet_name="HSSE_Data", index=False)
    workforce.to_excel(writer, sheet_name="Workforce_Data", index=False)

print("All 10 tables exported successfully!")
print(output_path)

All 10 tables exported successfully!
C:\Users\HP\Downloads\Dangote_Refinery_Cleaned_Data.xlsx